post_install() {
	
	applysys s6log.conf
	if ! getent passwd s6log >/dev/null; then
		useradd -u 19 -g 19 -d / -G log -c "S6 log user" -s /usr/bin/nologin s6log
	fi
	chown s6log:log /etc/s6/classic/uncaught-logs
	
	# This is needed at the boot time, if the fifo file doesn't exist
	# init system crash.
	if ! [ -p /etc/s6/classic/service/s6-svscan-log/fifo ]; then
		mkfifo /etc/s6/classic/service/s6-svscan-log/fifo
	fi
		
}
post_upgrade() {
	 post_install
}
